aws_region = "us-east-1"
environment = "production"
github_repository = "https://github.com/davidawcloudsecurity/learn-lovable-llm-sql"
github_access_token = "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"
custom_domain = ""